/* Node-only isolated transport fixtures. No real data, server or accounts. */
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const hub=require('../static/js/u1-create-earn-workspaces.js');
const id=n=>n.toString(16).padStart(32,'0');
function product(n=1,status='idea'){return {id:id(n),kind:'product',title:'Operator product '+n,version:1,archived:false,payload:{status,audience:'Operator audience',description:'Operator outcome',current_version:'',versions:[],notes:''}};}
function task(n=2,status='backlog'){return {id:id(n),kind:'launch',title:'Operator launch task',version:1,archived:false,payload:{status,product_id:id(1),due:'',notes:''}};}
function file(){const bytes=Buffer.from('isolated PDF fixture');return {id:id(3),name:'fixture.pdf',mime:'application/pdf',size:bytes.length,received:bytes.length,status:'ready',deleted:null,checksum:crypto.createHash('sha256').update(bytes).digest('hex'),bytes};}
function transport(products=[product()],launches=[],files=[file()]){const calls=[];return {calls,get:async(url)=>{calls.push({method:'GET',url});if(url.includes('/studio-pro'))return {success:true,templates:[{id:'course',title:'Course workbook',sections:['Outcome','Practice']}]};if(url.includes('/prism/summary'))return {success:true,files};if(url.includes('/prism/file')){const f=files[0];return {success:true,id:f.id,name:f.name,mime:f.mime,content:f.bytes.toString('base64')};}const u=new URL(url,'http://local.invalid'),kind=u.searchParams.get('kind'),wanted=u.searchParams.get('id');let rows=wanted?products.concat(launches).filter(r=>r.id===wanted):kind==='launch'?launches:products;const total=rows.length,offset=Number(u.searchParams.get('offset')||0);rows=rows.slice(offset,offset+200);return {success:true,records:rows,total,has_more:offset+rows.length<total};},post:async(url,body)=>{calls.push({method:'POST',url,body});return {success:true,record:body.action==='create'?{id:id(80),kind:body.kind,title:body.title,version:1,archived:false,payload:body.payload}:{...(body.id===id(2)?task():product()),version:body.expected_version+1,payload:{...product().payload,...body.payload}}};}};}
function model(products=[product()],tasks=[],files=[file()]){return hub.derive(products,tasks,files,[],[]);}

test('opening the model performs only GET and returns actual counts',async()=>{const t=transport([product(1,'review'),product(2,'ready')],[task()]);const m=await hub.createController(t).load();assert.equal(m.products.length,2);assert.equal(m.counts.ready,1);assert.equal(m.pending,1);assert.ok(t.calls.every(c=>c.method==='GET'));});
test('pagination loads every product rather than only the first page',async()=>{const rows=Array.from({length:250},(_,i)=>product(i+1));const t=transport(rows);assert.equal((await hub.readKind(t,'product')).length,250);assert.equal(t.calls.length,2);});
test('nonadvancing pagination is rejected',async()=>{await assert.rejects(()=>hub.readKind({get:async()=>({records:[],total:2,has_more:true})},'product'),/advance/);});
test('duplicate pages are rejected as changed data',async()=>{await assert.rejects(()=>hub.readKind({get:async()=>({records:[product()],total:3,has_more:true})},'product'),/changed/);});
test('unavailable products produce unavailable counts rather than zero',async()=>{const t=transport();const get=t.get;t.get=async u=>{if(u.includes('kind=product'))throw Error('Fixture offline');return get(u);};const m=await hub.createController(t).load();assert.equal(m.products,null);assert.equal(m.counts.idea,null);assert.match(m.errors.join(' '),/offline/);});
test('only complete ready PDF and ZIP metadata can be linked',()=>{const f=file();assert.equal(hub.readyFile(f),true);for(const bad of [{status:'uploading'},{received:0},{deleted:1},{mime:'text/html'},{checksum:''},{size:0}])assert.equal(hub.readyFile({...f,...bad}),false);});
test('product plans remain private idea records with operator text',()=>{const intent=hub.prepare('product',{title:'Original plan',audience:'Readers',description:'An outcome'},model());assert.equal(intent.body.kind,'product');assert.equal(intent.body.payload.status,'idea');assert.equal(intent.body.title,'Original plan');assert.equal('publish' in intent.body,false);});
test('review confirmation is required before any write',async()=>{const t=transport([]),c=hub.createController(t),intent=hub.prepare('product',{title:'New'},model([]));await assert.rejects(()=>c.commit(intent,false),/approve/);assert.equal(t.calls.length,0);});
test('matching product plans are rejected before create',async()=>{const p=product(),t=transport([p]),intent=hub.prepare('product',{title:p.title,audience:p.payload.audience,description:p.payload.description},model());await assert.rejects(()=>hub.createController(t).commit(intent,true),/already exists/);assert.equal(t.calls.filter(c=>c.method==='POST').length,0);});
test('one review cannot be submitted twice',async()=>{const t=transport([]),c=hub.createController(t),intent=hub.prepare('product',{title:'New private plan'},model([]));await c.commit(intent,true);await assert.rejects(()=>c.commit(intent,true),/already submitted/);assert.equal(t.calls.filter(c=>c.method==='POST').length,1);});
test('uncertain POST outcomes are not retried automatically',async()=>{const t=transport([]);t.post=async()=>{throw Error('Lost response');};const c=hub.createController(t),intent=hub.prepare('product',{title:'New'},model([]));await assert.rejects(()=>c.commit(intent,true),e=>e.uncertain===true);await assert.rejects(()=>c.commit(intent,true),/already submitted/);});
test('stale product revision blocks a new status mutation',async()=>{const p=product(),intent=hub.prepare('product-status',{status:'building'},model([p]),p.id),t=transport([{...p,version:2}]);await assert.rejects(()=>hub.createController(t).commit(intent,true),/changed after review/);assert.equal(t.calls.filter(c=>c.method==='POST').length,0);});
test('leaving the view during preflight prevents POST',async()=>{const t=transport([]),intent=hub.prepare('product',{title:'New'},model([]));await assert.rejects(()=>hub.createController(t).commit(intent,true,()=>false),/left before/);assert.equal(t.calls.filter(c=>c.method==='POST').length,0);});
test('ready and launched need a real current version file',()=>{for(const status of ['ready','launched'])assert.throws(()=>hub.prepare('product-status',{status},model(),id(1)),/Link a ready file/);});
test('version reviews include actual file ID, checksum and expected record revision',()=>{const f=file(),intent=hub.prepare('version',{file_id:f.id,version:'2.0'},model(),id(1));assert.equal(intent.body.expected_version,1);assert.equal(intent.body.payload.current_version,'2.0');assert.equal(intent.body.payload.versions[0].file_id,f.id);assert.match(intent.body.payload.versions[0].notes,new RegExp(f.checksum));});
test('same file/version links are not duplicated',()=>{const p=product(),f=file();p.payload.versions=[{version:'1.0',file_id:f.id}];assert.throws(()=>hub.prepare('version',{version:'1.0',file_id:f.id},model([p]),p.id),/already linked/);});
test('file bytes must match the exact reviewed checksum',async()=>{const f=file(),t=transport([product()],[],[f]);const result=await hub.verifiedDownload(t,f);assert.equal(Buffer.from(result.bytes).toString(),'isolated PDF fixture');await assert.rejects(()=>hub.verifiedDownload(t,{...f,checksum:'0'.repeat(64)}),/checksum changed/);});
test('launch records start in Backlog and preserve explicit ownership',()=>{const intent=hub.prepare('launch',{title:'Review rights',due:'2026-10-01'},model(),id(1));assert.equal(intent.body.payload.product_id,id(1));assert.equal(intent.body.payload.status,'backlog');});
test('a matching launch task cannot be created twice by the same review workflow',async()=>{const intent=hub.prepare('launch',{title:task().title},model(),id(1)),t=transport([product()],[task()]);await assert.rejects(()=>hub.createController(t).commit(intent,true),/already exists/);});
test('invalid IDs, unknown actions and overlong operator input cannot become writes',()=>{assert.throws(()=>hub.prepare('version',{file_id:'../bad',version:'1'},model(),id(1)),/Choose a complete/);assert.throws(()=>hub.prepare('product',{title:'X'.repeat(161)},model()),/limit/);assert.throws(()=>hub.prepare('publish',{},model(),id(1)),/supported local/);});
test('catalogue rendering escapes operator markup and labels earnings boundaries',()=>{const p=product();p.title='<img src=x onerror=alert(1)>';const html=hub.mainMarkup(model([p]),{mode:'earn',selected:p.id,query:'',filter:'all'});assert.ok(!html.includes('<img src=x'));assert.ok(html.includes('&lt;img'));assert.match(html,/not evidence of sales/);assert.match(html,/not a whole-library total/);assert.match(html,/subscriptions do not include separate provider API billing/);});
test('review summary names private-only effects and shows provenance',()=>{const intent=hub.prepare('version',{file_id:id(3),version:'2.0'},model(),id(1));const html=hub.editorMarkup({intent},model());assert.match(html,/SHA-256/);assert.match(html,/does not publish/);assert.match(html,/data-ce-approve/);});
test('Create and Earn register their own routes with lifecycle hooks without overriding editors',()=>{const registrations=[];const context=vm.createContext({window:{U1CoreViews:{register:(...args)=>registrations.push(args)}}});vm.runInContext(fs.readFileSync(path.join(__dirname,'../static/js/u1-create-earn-workspaces.js'),'utf8'),context);assert.deepEqual(registrations.map(r=>r[0]),['create','earn']);assert.ok(registrations.every(r=>typeof r[2].activate==='function'&&typeof r[2].deactivate==='function'));});

test('actual hub renderer owns one heading, browses read-only, and preserves cached unsaved forms',async()=>{
  class Node {constructor(){this.dataset={};this.value='';this.hidden=false;this.disabled=false;this.textContent='';this.innerHTML='';}hasAttribute(){return false;}focus(){}}
  class Host extends Node {constructor(){super();this.nodes=new Map();this.classList={add(){}};}querySelector(selector){if(!this.nodes.has(selector)){const node=new Node();node.querySelector=()=>new Node();this.nodes.set(selector,node);}return this.nodes.get(selector);}contains(){return true;}}
  const t=transport(),window={U1Data:t,U1CoreViews:{register(){}},confirm:()=>true};
  const context=vm.createContext({window,console,Date,URL,Blob,setTimeout,Uint8Array});
  vm.runInContext(fs.readFileSync(path.join(__dirname,'../static/js/u1-create-earn-workspaces.js'),'utf8'),context);
  const host=new Host();window.U1CreateEarn.renderEarn(host);await new Promise(setImmediate);
  assert.equal((host.innerHTML.match(/<h1>/g)||[]).length,1);
  assert.match(host.querySelector('[data-ce-content]').innerHTML,/Operator product 1/);
  const button={dataset:{ceAction:'product'},closest(){return this;}};
  await host.onclick({target:button});const pane=host.querySelector('[data-ce-editor]');assert.equal(pane.hidden,false);
  const input={name:'title',value:'Keep this unsaved review',hasAttribute(){return false;}};host.oninput({target:input});
  const form=pane.innerHTML;window.U1CreateEarn.deactivate(host);host.onclick=null;host.oninput=null;window.U1CreateEarn.activate(host);
  assert.equal(pane.innerHTML,form);assert.equal(input.value,'Keep this unsaved review');assert.equal(typeof host.onclick,'function');
  assert.equal(t.calls.filter(c=>c.method==='POST').length,0);
});
