'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('static/js/u1-core-workspaces.js', 'utf8');
const start = source.indexOf('window.U1CoreViews = Object.freeze(');
const end = source.indexOf("if (document.readyState === 'loading')", start);
assert.ok(start >= 0 && end > start, 'Native registry contract is present');
const hosts = new Map(), calls = [], extensions = new Map();
const document = {body:{dataset:{u1View:'media'}},getElementById:id=>hosts.get(id)||null};
const context = {window:{},document,extensions,views:{files:[]},mount:(id,host)=>calls.push({id,host}),icon:()=>''};
vm.runInNewContext(source.slice(start,end),context);
const registry=context.window.U1CoreViews, media={dataset:{filled:'1'}};
hosts.set('body-media',media);
registry.register('media',()=>{});
assert.equal(calls.length,1);assert.equal(calls[0].host,media);assert.equal(media.dataset.filled,'1');
assert.equal(registry.supports('media'),true);
const osint={dataset:{filled:'1'}};hosts.set('body-osint',osint);registry.register('osint',()=>{});
assert.equal(calls.length,1);assert.equal(osint.dataset.filled,undefined);
registry.register('files',()=>{});assert.equal(extensions.has('files'),false);
registry.register('broken',null);assert.equal(registry.supports('broken'),false);
registry.register('jobs',()=>{});assert.equal(registry.supports('jobs'),true);assert.equal(calls.length,1);
console.log('PASS 6 native registration and direct-entry contracts');
